### ISSUE TITLE
Detect/warn on unused function arguments

### ISSUE THREAD

**Issue by quinnj** [julia-vscode/StaticLint.jl#118]
When refactoring functions with lots of arguments, it can be really convenient/useful to know which arguments are now unused in order to cleanup. It'd be nice if the linter was able to signal that a function argument was unused in the function body. I know GoLang had a somewhat controversial strict enforcement of this, at least early on, and it's a common settings in lots of other compilers.

**Comment by davidanthoff** [comment]
In TypeScript this looks like this in VS Code:

![image](https://user-images.githubusercontent.com/1036561/81298375-fccb2800-9074-11ea-8fb2-9b2d308c6b56.png)

`parB` here gets a different color to indicate that it is nowhere used. Maybe that would be a nice way to visualize that?

I don't fully understand what is happening in the TypeScript case, though... If I hover over the argument, I get a message explaining that this one is not used, but that message does not show up in the problems list. Does that mean it is not a diagnostic what they are using? They also seem to offer code actions on this, maybe that explains the little dotted underline and the hover info?

**Comment by ZacLN** [comment]
I think it may be added as a https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions or something similar, not quite sure but I agree this would b enice
