### ISSUE TITLE
Rule for nothing comparisons

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/StaticLint.jl#16]
We could look for comparisons with ``nothing`` that use ``==`` instead of ``===`` and offer an automatic fix. Like what Jeff did manually in https://github.com/JuliaLang/julia/pull/30673.

There are others that we could also catch: ``!=`` to ``!==``, and then do all of this for ``nothing`` and ``missing``.

**Comment by ZacLN** [comment]
Is this supposed to be performant?

**Comment by ZacLN** [comment]
addressed
