### ISSUE TITLE
API functions for CLI / REPL usage

### ISSUE THREAD

**Issue by TeroFrondelius** [julia-vscode/StaticLint.jl#17]
I spent few hours to learn the internals of StaticLint.jl. In my mind we would need the following functions:
```julia
using StaticLint 

lintpkg("MyPackage") # for linting an entire package
lintfile("my_file.jl") # for linting a file
lintstr("my string") # for linting a string
```
What you think?

**Comment by camenpihor** [comment]
Hiya! Just checking in on this since I think it would be pretty helpful! I'm happy to lend a hand, if that would helpful? If so! Just let me know what I can do! :)

**Comment by ZacLN** [comment]
I'm closing this, do add comments [here](https://github.com/julia-vscode/StaticLint.jl/pull/239) on interface, documentation etc
