### ISSUE TITLE
Fields in `@NamedTuple`

### ISSUE THREAD

**Issue by dojt** [julia-vscode/StaticLint.jl#210]
It seems as if the `@NamedTuple` isn't recognized yet:
![image](https://user-images.githubusercontent.com/57910358/89098551-5ed7c700-d3f1-11ea-8470-26b9a21773cb.png)

Line 1: The Julia 1.4 style definition works fine.
Line 2: The fields in the `@NamedTuple{}` are not recognized by the linter ("Missing references" on `a`,`b`)
Line 3: The short-form function definition containing @NamedTuple{} type assert isn't recognized ("Missing reference" on `h`)

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/StaticLint.jl/pull/203/commits/70fc32197931a01fe71dbf5fda3c6ed0fd6c6ccf
