### ISSUE TITLE
Possible method call error showing up on some simple code

### ISSUE THREAD

**Issue by dmalyuta** [julia-vscode/StaticLint.jl#256]
I am using:
- OS: Ubuntu 20.04.1 LTS
- Julia: 1.5.3
- StaticLint: [b3cc710f] StaticLint v7.0.0
- SymbolServer: [cf896787] SymbolServer v6.0.1

The following code seems problematic:
```
abstract type MyType end

mutable struct Bar<:MyType
    val::Integer
end

function multiply!(x::T, y::Integer)::Nothing where {T<:MyType}
    x.val *= y
    return nothing
end

z = Bar(2)
multiply!(z, 3)

println(z.val)
```

Here is what StaticLint shows:
![image](https://user-images.githubusercontent.com/12475811/106536486-6ade3780-64ad-11eb-9f12-1c8103c25bac.png)

It seems that StaticLint has a history of issues with this kind of error: [here](https://github.com/julia-vscode/julia-vscode/issues/1218), [here](https://github.com/julia-vscode/julia-vscode/issues/1576), and [here](https://discourse.julialang.org/t/vscode-showing-possible-method-call-error-for-working-code/43219)

**Comment by pfitzseb** [comment]
I think there are two issues here:
1. `function multiply!(x::T, y::Integer)::Nothing where {T<:MyType}` (needs both the `where` clause and return type annotation) being treated as a call.
2. We can't infer the type of `z`. 

So
```
function multiply!(x::T, y::Integer) where T <: MyType # no return type annotation
    x.val *= y
    return nothing
end

function f(z::Bar) # make sure we can figure out the type of z
    multiply!(z, 3)
end
```
works just fine.

**Comment by dmalyuta** [comment]
Just to be clear, your point 1 is a current issue with StaticLint? Do we agree that `function multiply!(x::T, y::Integer)::Nothing where {T<:MyType}` should be interpreted as a function signature? If I remove the `::Nothing`, then the following code works without any errors reported by StaticLint:

```
abstract type MyType end

mutable struct Bar<:MyType
    val::Integer
end

function multiply!(x::T, y::Integer) where {T<:MyType}
    x.val *= y
    return nothing
end

z = Bar(2)
multiply!(z, 3)

println(z.val)
```

**Comment by ZacLN** [comment]
It's just a bug, I'll fix it

**Comment by dmalyuta** [comment]
Hmm I think that the fix by @ZacLN has the inadvertent side-effect of suppressing warnings such as `An argument is included in a function signature but not used within its body.` when the function signature contains the `where {T<:...}` syntax. For example, for the following function StaticLint does not show any warnings:
```
function multiply!(x::T, y::Integer, z::Integer)::Nothing where {T<:MyType}
    x.val *= y
    return nothing
end
```

On the other hand, the following function does show a warning that the `z` argument is not used within its body:
```
function multiply!(x::Bar, y::Integer, z::Integer)::Nothing
    x.val *= y
    return nothing
end
```
