### ISSUE TITLE
Lots of StackOverflowError

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/StaticLint.jl#29]
In the telemetry for v0.12.0, I hope [this](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22%3A%22_autocluster_283492bc-45c9-4dfa-b264-95d249dcb3b7%22%2C%22cacheId%22%3A%229f82f18b-4405-45a9-ab0c-55734ae0cdea%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222019-08-13T23%3A50%3A00.000Z%22%2C%22createdTime%22%3A%222019-08-13T23%3A49%3A38.402Z%22%2C%22isInitialTime%22%3Afalse%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D%7D/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D) link works.

**Comment by ZacLN** [comment]
hopefully fixed by: https://github.com/julia-vscode/StaticLint.jl/commit/7264073d1b2d7111539b2bf756d6a33acb746f29
