### ISSUE TITLE
"Possible method call error" for function arguments

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/StaticLint.jl#294]
![image](https://user-images.githubusercontent.com/6933510/121517227-668fd100-c9ef-11eb-8d5a-6e3752f28389.png)

**Comment by davidanthoff** [comment]
I really think we shouldn't show a warning like that, it just clutters things. I think the linter should only ever warn if it is darn sure that there is a problem.

**Comment by pfitzseb** [comment]
Seems to be fixed:
![image](https://user-images.githubusercontent.com/6735977/133059957-228e0bc4-de5b-4b3a-af51-fa3b627ea249.png)
