### ISSUE TITLE
Add lint for `for i=1:length(v)`

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/StaticLint.jl#337]
After reading <https://yuri.is/not-julia/>, one takeaway is that this pattern is a frequent source of bugs when combined with OffsetArrays (especially with the use of `@inbounds`). In almost all cases, `1:length(v)` should be replaced with `eachindex(v)`. If there's worry that this lint would be too intrusive for cases where you really want to iterate over the length of an array rather than its indices, this lint could be conditional on `@inbounds` being present.

**Comment by pfitzseb** [comment]
With https://github.com/julia-vscode/StaticLint.jl/pull/338 and https://github.com/julia-vscode/LanguageServer.jl/pull/1086:
![image](https://user-images.githubusercontent.com/6735977/168799917-7aa5ccb7-d16f-4128-8768-6aceb825dc62.png)
