### ISSUE TITLE
support for const fields of Julia 1.8?

### ISSUE THREAD

**Issue by mind6** [julia-vscode/StaticLint.jl#340]
Currently if using 1.8RC3, the following gives a parse error:
```julia
mutable struct S
    const x::Int
    y::Int
end
```
But it's allowed in 1.8 as one of the new language features: https://github.com/JuliaLang/julia/blob/v1.8.0-beta1/NEWS.md

**Comment by pfitzseb** [comment]
This is fixed on master via https://github.com/julia-vscode/CSTParser.jl/pull/337 and https://github.com/julia-vscode/StaticLint.jl/pull/336
![image](https://user-images.githubusercontent.com/6735977/180158960-76d5e837-ac47-4639-be4c-3ab177ef0edc.png)
