### ISSUE TITLE
Recommend pairs over enumerate

### ISSUE THREAD

**Issue by jariji** [julia-vscode/StaticLint.jl#347]
`pairs` is safer than `enumerate` for OffsetArrays.

```jl
julia> collect(enumerate(OffsetArray([10,20], 5)))
2-element Vector{Tuple{Int64, Int64}}:
 (1, 10)
 (2, 20)

julia> collect(pairs(OffsetArray([10,20], 5)))
2-element OffsetArray(::Vector{Pair{Int64, Int64}}, 6:7) with eltype Pair{Int64, Int64} with indices 6:7:
 6 => 10
 7 => 20
```

**Comment by fredrikekre** [comment]
They have different purposes, sometimes you want to count from 1, and then you want `enumerate`. If `enumerate` was simply an unsafe version of pairs it wouldn't exist in the language most likely.
