### ISSUE TITLE
StaticLint 1.0.2: UndefVarError: Scope not defined

### ISSUE THREAD

**Issue by Sh4pe** [julia-vscode/StaticLint.jl#40]
When trying to include `StaticLint` version 1.0.2, I get this error:

```julia
julia> using StaticLint
[ Info: Precompiling StaticLint [b3cc710f-9c33-5bdb-a03d-a94903873e97]
ERROR: LoadError: UndefVarError: Scope not defined
# ...
```

Indeed, the 1.0.2 version [uses Scope](https://github.com/julia-vscode/StaticLint.jl/blob/a144dad457f39ef7f67d8914014d3c5d28f22332/src/StaticLint.jl#L5) from `CSTParser`, but the current version of [CSTParser](https://github.com/julia-vscode/CSTParser.jl/blob/master/src/CSTParser.jl) does not seem to export a struct named `Scope`.

Note that I've stumbled across this problem while debugging a problem in the Julia Language Server for VSCode, see e.g. [julia-vscode/issues/892](https://github.com/julia-vscode/julia-vscode/issues/892).

**Comment by davidanthoff** [comment]
We had a little messup with our releases. If you update your packages, you should now get a consistent set of versions again.
