### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/StaticLint.jl#44]
They seem to fail right now. Not clear whether we just need to tag new versions of upstream packages, or something more tricky? I'll try to figure out whether things work with newer versions of upstream packages next.

**Comment by davidanthoff** [comment]
Ok, just tested this with all the latest `master` versions of the other packages, and tests still fail, so I think these are just genuine test failures, and I hand it over to @ZacLN  :)

**Comment by ZacLN** [comment]
fixed
